spring.datasource.url=${DB_URL}&prepareThreshold=0
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

jwt.secret=jfkgieodpslxmanqjwkfltrioplkjmna
jwt.expiration=36000000

cors.allowed-origins=*